// import localFont from "next/font/local";
import { Anton } from 'next/font/google'
import "./globals.css";
import Navigation from "./components/Navigation/Navigation";
import { AboutProvider } from '@/context/AboutContext';
import { ManagementProvider } from '@/context/ManagementContext';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={anton.className}
      >
        <Navigation />
        <AboutProvider>
          <ManagementProvider>
            {children}
          </ManagementProvider>
        </AboutProvider>
      </body>
    </html>
  );
}
